// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/karyawan": {
            "put": {
                "description": "Update Karyawan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Karyawan"
                ],
                "summary": "Put Karyawan Data",
                "parameters": [
                    {
                        "description": "Karyawan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateKaryawanRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Add new Karyawan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Karyawan"
                ],
                "summary": "Post Karyawan Data",
                "parameters": [
                    {
                        "description": "Karyawan",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SaveKaryawanRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/karyawan/list": {
            "get": {
                "description": "Get All Karyawan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Karyawan"
                ],
                "summary": "Get All Karyawan Data",
                "responses": {}
            }
        },
        "/karyawan/{id}": {
            "get": {
                "description": "Get Karyawan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Karyawan"
                ],
                "summary": "Get Karyawan Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Karyawan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Karyawan"
                ],
                "summary": "Delete Karyawan Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Karyawan ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/karyawanTraining": {
            "put": {
                "description": "Update KaryawanTraining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryawanTraining"
                ],
                "summary": "Put KaryawanTraining Data",
                "parameters": [
                    {
                        "description": "KaryawanTraining",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateKaryawanTrainingRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Add new KaryawanTraining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryawanTraining"
                ],
                "summary": "Post KaryawanTraining Data",
                "parameters": [
                    {
                        "description": "KaryawanTraining",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SaveKaryawanTrainingRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/karyawanTraining/list": {
            "get": {
                "description": "Get All KaryawanTraining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryawanTraining"
                ],
                "summary": "Get All KaryawanTraining Data",
                "responses": {}
            }
        },
        "/karyawanTraining/{id}": {
            "get": {
                "description": "Get KaryawanTraining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryawanTraining"
                ],
                "summary": "Get KaryawanTraining Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete KaryawanTraining",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "KaryawanTraining"
                ],
                "summary": "Delete KaryawanTraining Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "KaryawanTraining ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/rekening": {
            "put": {
                "description": "Update Rekening",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rekening"
                ],
                "summary": "Put Rekening Data",
                "parameters": [
                    {
                        "description": "Rekening",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateRekeningRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Add new Rekening",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rekening"
                ],
                "summary": "Post Rekening Data",
                "parameters": [
                    {
                        "description": "Rekening",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SaveRekeningRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/rekening/list": {
            "get": {
                "description": "Get All Rekening",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rekening"
                ],
                "summary": "Get All Rekening Data",
                "responses": {}
            }
        },
        "/rekening/{id}": {
            "get": {
                "description": "Get Rekening",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rekening"
                ],
                "summary": "Get Rekening Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Rekening",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Rekening"
                ],
                "summary": "Delete Rekening Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Rekening ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/training": {
            "put": {
                "description": "Update Training",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Put Training Data",
                "parameters": [
                    {
                        "description": "Training",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.UpdateTrainingRequest"
                        }
                    }
                ],
                "responses": {}
            },
            "post": {
                "description": "Add new Training",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Post Training Data",
                "parameters": [
                    {
                        "description": "Training",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dtos.SaveTrainingRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/training/list": {
            "get": {
                "description": "Get All Training",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Get All Training Data",
                "responses": {}
            }
        },
        "/training/{id}": {
            "get": {
                "description": "Get Training",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Get Training Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID",
                        "name": "id",
                        "in": "path"
                    }
                ],
                "responses": {}
            },
            "delete": {
                "description": "Delete Training",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Training"
                ],
                "summary": "Delete Training Data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Training ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "dtos.KaryawanRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dtos.RekeningKaryawan": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dtos.SaveDetailKaryawan": {
            "type": "object",
            "properties": {
                "nik": {
                    "type": "string"
                },
                "npwp": {
                    "type": "string"
                }
            }
        },
        "dtos.SaveKaryawanRequest": {
            "type": "object",
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "detailKaryawan": {
                    "$ref": "#/definitions/dtos.SaveDetailKaryawan"
                },
                "dob": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.SaveKaryawanTrainingRequest": {
            "type": "object",
            "properties": {
                "karyawan": {
                    "$ref": "#/definitions/dtos.KaryawanRequest"
                },
                "tanggal": {
                    "type": "string"
                },
                "training": {
                    "$ref": "#/definitions/dtos.TrainingRequest"
                }
            }
        },
        "dtos.SaveRekeningKaryawan": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dtos.SaveRekeningRequest": {
            "type": "object",
            "properties": {
                "jenis": {
                    "type": "string"
                },
                "karyawan": {
                    "$ref": "#/definitions/dtos.SaveRekeningKaryawan"
                },
                "nama": {
                    "type": "string"
                },
                "rekening": {
                    "type": "string"
                }
            }
        },
        "dtos.SaveTrainingRequest": {
            "type": "object",
            "properties": {
                "pengajar": {
                    "type": "string"
                },
                "tema": {
                    "type": "string"
                }
            }
        },
        "dtos.TrainingRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateDetailKaryawan": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "nik": {
                    "type": "string"
                },
                "npwp": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateKaryawanRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "detailKaryawan": {
                    "$ref": "#/definitions/dtos.UpdateDetailKaryawan"
                },
                "dob": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "nama": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateKaryawanTrainingRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "integer"
                },
                "karyawan": {
                    "$ref": "#/definitions/dtos.KaryawanRequest"
                },
                "tanggal": {
                    "type": "string"
                },
                "training": {
                    "$ref": "#/definitions/dtos.TrainingRequest"
                }
            }
        },
        "dtos.UpdateRekeningRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "alamat": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "jenis": {
                    "type": "string"
                },
                "karyawan": {
                    "$ref": "#/definitions/dtos.RekeningKaryawan"
                },
                "nama": {
                    "type": "string"
                },
                "rekening": {
                    "type": "string"
                }
            }
        },
        "dtos.UpdateTrainingRequest": {
            "type": "object",
            "required": [
                "id"
            ],
            "properties": {
                "id": {
                    "type": "string"
                },
                "pengajar": {
                    "type": "string"
                },
                "tema": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
